version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    networks:
      - app-network
    environment:
      VITE_API_URL: http://backend:8000  # Point frontend to backend API service
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    networks:
      - app-network
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      RUNNING_IN_DOCKER: "true"
    depends_on:
      - redis

  redis:
    image: redis:alpine
    volumes:
      - redis-data:/data
    ports:
      - "6379:6379"
    networks:
      - app-network

volumes:
  redis-data:

networks:
  app-network:
