name: Backend Lint and Format

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint-format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install -r dev-requirements.txt
        working-directory: ./backend

      - name: Lint and format code
        run: |
          black --check --line-length 120 .
          flake8 --ignore=F401 --max-line-length=120
        working-directory: ./backend

      - name: Run black (check only)
        run: black --check --line-length 120 .
        working-directory: ./backend

      - name: Run isort (check only)
        run: isort --check-only .
        working-directory: ./backend

      - name: Run black (auto-fix)
        run: black --line-length 120 .
        working-directory: ./backend

      - name: Run isort (auto-fix)
        run: isort .
        working-directory: ./backend
